---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      apt:
        name: python-pip
        state: latest
    - name: Install docker
      apt:
        name: docker
        state: latest
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: latest
    - name: Start the container
      docker_container:
        name: myapp1
        image: "chaithramanjunatha/myapp1:${{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
