---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      apt:
        name: python-pip
        state: present
        tasks:
    - name: Removing Python libraries
      pip:
          name: NumPy,SciPy
          state: absent
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      apt:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: hariapp
        image: "chaithramanjunatha/myapp1:${{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
