---
- hosts: dev
  become: True
  tasks:
   - name: Installing required version of python library in Ansible
     pip:
      name: nltk
      version: '3.0.0'
   - name: Install python pip
      apt:
        name: python3-pip
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: myapp1
        image: "chaithramanjunatha/myapp1:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
